management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST, PUT, DELETE
        allowed-headers: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8080
